# Generated by Django 5.1.7 on 2025-03-26 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_regions_customuser_region'),
        ('posts', '0005_post_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.regions'),
        ),
    ]
