# Generated by Django 5.2 on 2025-04-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_message_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='message_html',
        ),
    ]
