# Generated by Django 5.0.3 on 2025-03-22 14:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_customuser_is_blocked_customuser_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=0, editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
