# Generated by Django 5.0.3 on 2025-03-22 14:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_customuser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='username', unique=True),
        ),
    ]
