# Generated by Django 5.0.3 on 2025-03-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_customuser_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='slug',
        ),
    ]
