# Generated by Django 5.0.3 on 2025-03-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_ticket_created_at_alter_ticket_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
