# Generated by Django 5.0.2 on 2024-03-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='group_backgrounds/'),
        ),
    ]
