# Generated by Django 5.1.7 on 2025-03-29 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_grouppost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppost',
            name='region',
        ),
        migrations.AddField(
            model_name='grouppost',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
    ]
