# Generated by Django 5.2 on 2025-04-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_remove_grouppost_region_grouppost_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='message_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
