# Generated by Django 5.2 on 2025-04-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_grouppost_message_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppost',
            name='message_html',
        ),
    ]
