# Generated by Django 5.0.3 on 2025-03-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
    ]
