# Generated by Django 5.0.3 on 2025-03-23 16:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=1, editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
