from .settings import settings
from .profile import profile
from .index import index
from .delete_post import delete_post
from .edit_post import edit_post
from .add_friend import add_friend
from .friend_list import friend_list
from .delete_friend import delete_friend
from .accept_friend import accept_friend
from .reject_friend import reject_friend
from .edit_profile import edit_profile
from .change_password import change_password