from .profile import profile
from .delete_post import delete_post
from .edit_post import edit_post
from .settings import settings
from .delete_comment import delete_comment
from .write import write
from .add_friend import add_friend
from .notifications import notifications
from .accept_request import accept_request
from .reject_request import reject_request
from .delete_friend import delete_friend